name: docker-compose CI

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the docker-compose stack
      run: docker-compose build
    - name: Launch containers
      run: docker-compose up -d
    - name: Check running containers
      run: docker ps -a
    - name: Check logs
      run: docker logs backend
